const TODO_ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_TODOS: "SET_TODOS",
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  SET_ERROR: "SET_ERROR",
  SET_EDITING_TODO: "SET_EDITING_TODO",
}

export default TODO_ACTIONS;